package com.nathaniel.utility.greendao;

import com.nathaniel.utility.entity.AntivirusEntity;
import com.nathaniel.utility.entity.FileEntity;
import com.nathaniel.utility.entity.PackageEntity;
import com.nathaniel.utility.entity.PermissionEntity;
import com.nathaniel.utility.entity.SpecimenEntity;
import com.nathaniel.utility.entity.SummaryEntity;
import com.nathaniel.utility.entity.TaskEntity;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig antivirusEntityDaoConfig;
    private final DaoConfig fileEntityDaoConfig;
    private final DaoConfig packageEntityDaoConfig;
    private final DaoConfig permissionEntityDaoConfig;
    private final DaoConfig specimenEntityDaoConfig;
    private final DaoConfig summaryEntityDaoConfig;
    private final DaoConfig taskEntityDaoConfig;

    private final AntivirusEntityDao antivirusEntityDao;
    private final FileEntityDao fileEntityDao;
    private final PackageEntityDao packageEntityDao;
    private final PermissionEntityDao permissionEntityDao;
    private final SpecimenEntityDao specimenEntityDao;
    private final SummaryEntityDao summaryEntityDao;
    private final TaskEntityDao taskEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
        daoConfigMap) {
        super(db);

        antivirusEntityDaoConfig = daoConfigMap.get(AntivirusEntityDao.class).clone();
        antivirusEntityDaoConfig.initIdentityScope(type);

        fileEntityDaoConfig = daoConfigMap.get(FileEntityDao.class).clone();
        fileEntityDaoConfig.initIdentityScope(type);

        packageEntityDaoConfig = daoConfigMap.get(PackageEntityDao.class).clone();
        packageEntityDaoConfig.initIdentityScope(type);

        permissionEntityDaoConfig = daoConfigMap.get(PermissionEntityDao.class).clone();
        permissionEntityDaoConfig.initIdentityScope(type);

        specimenEntityDaoConfig = daoConfigMap.get(SpecimenEntityDao.class).clone();
        specimenEntityDaoConfig.initIdentityScope(type);

        summaryEntityDaoConfig = daoConfigMap.get(SummaryEntityDao.class).clone();
        summaryEntityDaoConfig.initIdentityScope(type);

        taskEntityDaoConfig = daoConfigMap.get(TaskEntityDao.class).clone();
        taskEntityDaoConfig.initIdentityScope(type);

        antivirusEntityDao = new AntivirusEntityDao(antivirusEntityDaoConfig, this);
        fileEntityDao = new FileEntityDao(fileEntityDaoConfig, this);
        packageEntityDao = new PackageEntityDao(packageEntityDaoConfig, this);
        permissionEntityDao = new PermissionEntityDao(permissionEntityDaoConfig, this);
        specimenEntityDao = new SpecimenEntityDao(specimenEntityDaoConfig, this);
        summaryEntityDao = new SummaryEntityDao(summaryEntityDaoConfig, this);
        taskEntityDao = new TaskEntityDao(taskEntityDaoConfig, this);

        registerDao(AntivirusEntity.class, antivirusEntityDao);
        registerDao(FileEntity.class, fileEntityDao);
        registerDao(PackageEntity.class, packageEntityDao);
        registerDao(PermissionEntity.class, permissionEntityDao);
        registerDao(SpecimenEntity.class, specimenEntityDao);
        registerDao(SummaryEntity.class, summaryEntityDao);
        registerDao(TaskEntity.class, taskEntityDao);
    }

    public void clear() {
        antivirusEntityDaoConfig.clearIdentityScope();
        fileEntityDaoConfig.clearIdentityScope();
        packageEntityDaoConfig.clearIdentityScope();
        permissionEntityDaoConfig.clearIdentityScope();
        specimenEntityDaoConfig.clearIdentityScope();
        summaryEntityDaoConfig.clearIdentityScope();
        taskEntityDaoConfig.clearIdentityScope();
    }

    public AntivirusEntityDao getAntivirusEntityDao() {
        return antivirusEntityDao;
    }

    public FileEntityDao getFileEntityDao() {
        return fileEntityDao;
    }

    public PackageEntityDao getPackageEntityDao() {
        return packageEntityDao;
    }

    public PermissionEntityDao getPermissionEntityDao() {
        return permissionEntityDao;
    }

    public SpecimenEntityDao getSpecimenEntityDao() {
        return specimenEntityDao;
    }

    public SummaryEntityDao getSummaryEntityDao() {
        return summaryEntityDao;
    }

    public TaskEntityDao getTaskEntityDao() {
        return taskEntityDao;
    }

}
